[package]
name = "test-thingy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-codegen = { version = "0.1.0", path = "../aoc-codegen" }
aoc-lib = { version = "0.1.0", path = "../aoc-lib" }
